name:                tree-edit-distance
version:             0.1.0.0
github:              tkvogt/tree-edit-distance
license:             BSD-3-Clause
author:              Tillmann Vogt
maintainer:          "tillk.vogt@gmail.com"
copyright:           "2024 Tillmann Vogt"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tkvogt/tree-edit-distance#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- intmap-graph
- text
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tree-edit-distance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tree-edit-distance

tests:
  tree-edit-distance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tree-edit-distance
